### ISSUE TITLE
Evolutions of the Array/YAML format

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#121]
The array/YAML format is too limited and confusing, it needs to be more explicit and powerful.
- **differentiating values and objects**

``` yaml
foo:
```

Is it a `null` value entry or the declaration of a `foo` class with default configuration?

-> how to differentiate?

Same problem for:

``` yaml
# this is not a service, this is a value (array)
foo:
  constructor: bar
```

Symfony separates the declarations of parameters and services:

``` yaml
parameters:
  foo:
services:
  bar:
```

I don't really like the difference being made between the 2 types, a container can contain anything and should differentiate. However, is there another solution to this problem?
- **entry "links"**

Today, constructor and method parameters _have to be_ an entry name. You cannot specify a value directly. By using a special character, we could differentiate between a value and a link to another entry:

``` yaml
MyClass:
  constructor:
    foo: "a string"
    bar: "@some.other.entry"
```

Inspired by Symfony.
- **dynamic parameters**

Symfony has the concept of parameters whose values depends on the environment. They can be used in YAML:

``` yaml
MyClass:
  constructor: [ "%db.password%" ]
```

---

Questions:
1. Should the YAML format be kept? Symfony introduces the ExpressionEngine to write "php code" in YAML, is it sane? Is it a sign that YAML is by essence too limited and that PHP code should be used?

pros:
- PHP code allows to write PHP code ;) (expressions, anonymous functions…)
- PHP code allows autocompletion and refactoring support from IDEs
- PHP 5.5 allows to use short class names (`MyClass::class`)
- PHP code is familiar to everyone

cons:
- PHP array config is more verbose
- PHP array config is less easy to read
