### ISSUE TITLE
Impossible to define "null" value with YAML

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/PHP-DI#95]
YAML supports null values with:

``` yaml
nullparam: null
nullparam: ~
nullparam:
```

But it seems PHP-DI doesn't read them correctly (see https://github.com/mnapoli/PHP-DI/issues/79#issuecomment-22245910)
